name: Link Check
on:
  push: { branches: [main] }
  pull_request:
  schedule: [{ cron: "0 6 * * 1" }]   # weekly
  workflow_dispatch:

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v1
        with:
  args: --verbose --no-progress --exclude-mail --retry 2 --timeout 20 --exclude linkedin.com --exclude twitter.com --exclude x.com .
